FROM --platform=$BUILDPLATFORM node:18.20.1-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

ARG VITE_API_BASE_URL=
ARG VITE_ENABLE_LOGIN_GUARD=false
ARG VITE_LOGIN_STATUS_PATH=/auth/login
ARG VITE_LOGIN_PAGE_URL=/auth/login
ARG VITE_WRITE_API_KEY=
ARG VITE_UPLOAD_TIMEOUT_MS=300000
ARG VITE_COMPETITION_START_AT=2026-05-24T08:00:00-07:00
ARG VITE_COMPETITION_END_AT=2026-06-15T00:00:00-07:00
ARG VITE_COMPETITION_SCHEDULE_TEXT=2026/5/24 8:00--2026/6/14

ENV VITE_API_BASE_URL=$VITE_API_BASE_URL
ENV VITE_ENABLE_LOGIN_GUARD=$VITE_ENABLE_LOGIN_GUARD
ENV VITE_LOGIN_STATUS_PATH=$VITE_LOGIN_STATUS_PATH
ENV VITE_LOGIN_PAGE_URL=$VITE_LOGIN_PAGE_URL
ENV VITE_WRITE_API_KEY=$VITE_WRITE_API_KEY
ENV VITE_UPLOAD_TIMEOUT_MS=$VITE_UPLOAD_TIMEOUT_MS
ENV VITE_COMPETITION_START_AT=$VITE_COMPETITION_START_AT
ENV VITE_COMPETITION_END_AT=$VITE_COMPETITION_END_AT
ENV VITE_COMPETITION_SCHEDULE_TEXT=$VITE_COMPETITION_SCHEDULE_TEXT

RUN npm run build

FROM nginx:1.27-alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80
